sources:
  # --- Core competitors (RSS only) ---
  - name: ClickHouse Blog
    kind: rss
    category: blog
    url: https://clickhouse.com/rss.xml

  - name: ScyllaDB Blog
    kind: rss
    category: blog
    url: https://www.scylladb.com/feed/

  - name: Yugabyte Blog
    kind: rss
    category: blog
    url: https://www.yugabyte.com/blog/feed/

  - name: PingCAP (TiDB) Blog
    kind: rss
    category: blog
    url: https://www.pingcap.com/blog/feed/

  - name: CockroachDB Blog
    kind: rss
    category: blog
    url: https://www.cockroachlabs.com/blog/index.xml

  - name: DataStax Blog
    kind: rss
    category: blog
    url: https://www.datastax.com/blog/rss.xml

  - name: MariaDB (Resources Blog)
    kind: rss
    category: blog
    url: https://mariadb.com/resources/blog/feed/

  # Redis: official blog is on redis.io; if this ever fails, swap to HTML scraping
  - name: Redis Blog
    kind: rss
    category: blog
    url: https://redis.com/blog/feed/

  # Databricks: use official release-notes feed (their blog has no public RSS)
  - name: Databricks Release Notes
    kind: rss
    category: release-notes
    url: https://docs.databricks.com/en/release-notes/index.xml

  # --- MongoDB newsroom + security ---
  - name: MongoDB Security Bulletins
    kind: rss
    category: security
    url: https://www.mongodb.com/alerts/rss

  - name: MongoDB Press Releases
    kind: rss
    category: press
    url: https://investors.mongodb.com/rss/press-releases.xml

  # --- Broader DB news you asked for ---
  - name: DB-Engines Ranking
    kind: rss
    category: news-aggregate
    url: https://db-engines.com/en/rss/ranking.xml

  - name: InfoQ – Database
    kind: rss
    category: news
    url: https://feed.infoq.com/database

  - name: PostgreSQL News (official)
    kind: rss
    category: news
    url: https://www.postgresql.org/news.rss

  - name: Planet PostgreSQL (community aggregator)
    kind: rss
    category: news-aggregate
    url: https://planet.postgresql.org/rss20.xml

  - name: MySQL Official Blog
    kind: rss
    category: blog
    url: https://blogs.oracle.com/mysql/rss

  - name: Google Cloud – BigQuery Release Notes
    kind: rss
    category: release-notes
    url: https://cloud.google.com/feeds/bigquery-release-notes.xml

  - name: Google Cloud – Cloud Spanner Release Notes
    kind: rss
    category: release-notes
    url: https://cloud.google.com/feeds/cloud-spanner-release-notes.xml

  - name: AWS Database Blog
    kind: rss
    category: news
    url: https://aws.amazon.com/blogs/database/feed/
