sources:
  # --- Blogs (unchanged) ---
  - name: ClickHouse Blog
    kind: rss
    category: blog
    url: https://clickhouse.com/rss.xml

  - name: ScyllaDB Blog
    kind: rss
    category: blog
    url: https://www.scylladb.com/feed/

  - name: Yugabyte Blog
    kind: rss
    category: blog
    url: https://www.yugabyte.com/blog/feed/

  - name: PingCAP (TiDB) Blog
    kind: rss
    category: blog
    url: https://www.pingcap.com/blog/feed/

  - name: CockroachDB Blog
    kind: rss
    category: blog
    url: https://www.cockroachlabs.com/blog/index.xml

  - name: DataStax Blog
    kind: rss
    category: blog
    url: https://www.datastax.com/blog/rss.xml

  - name: MariaDB (Resources Blog)
    kind: rss
    category: blog
    url: https://mariadb.com/resources/blog/feed/

  - name: Redis Blog
    kind: rss
    category: blog
    url: https://redis.com/blog/feed/

  - name: Databricks Release Notes
    kind: rss
    category: release
    url: https://docs.databricks.com/en/release-notes/index.xml

  # --- MongoDB official (news-like) ---
  - name: MongoDB Security Bulletins
    kind: rss
    category: news
    url: https://www.mongodb.com/alerts/rss

  - name: MongoDB Press Releases
    kind: rss
    category: news
    url: https://investors.mongodb.com/rss/press-releases.xml

  # --- Broader DB news ---
  - name: DB-Engines Ranking
    kind: rss
    category: news
    url: https://db-engines.com/en/rss/ranking.xml

  - name: InfoQ – Database
    kind: rss
    category: news
    url: https://feed.infoq.com/database

  - name: PostgreSQL News (official)
    kind: rss
    category: news
    url: https://www.postgresql.org/news.rss

  - name: Planet PostgreSQL
    kind: rss
    category: news
    url: https://planet.postgresql.org/rss20.xml

  - name: MySQL Official Blog
    kind: rss
    category: blog
    url: https://blogs.oracle.com/mysql/rss

  - name: BigQuery Release Notes
    kind: rss
    category: release
    url: https://cloud.google.com/feeds/bigquery-release-notes.xml

  - name: Cloud Spanner Release Notes
    kind: rss
    category: release
    url: https://cloud.google.com/feeds/cloud-spanner-release-notes.xml

  # =========================
  #        EVENTS & WEBINARS
  # =========================

  # ClickHouse — Events (HTML)
  - name: ClickHouse Events
    kind: html
    category: event
    url: https://clickhouse.com/events
    selectors:
      item: "main a[href*='/events/']"
      title: "a"
      link_attr: href
      date: null

  # ScyllaDB — Events (likely WP; RSS exists)
  - name: ScyllaDB Events
    kind: rss
    category: event
    url: https://www.scylladb.com/events/feed/

  # Yugabyte — Events (try RSS; fall back to HTML if needed)
  - name: Yugabyte Events
    kind: rss
    category: event
    url: https://www.yugabyte.com/events/feed/

  # PingCAP — Community Events (HTML)
  - name: PingCAP Events
    kind: html
    category: event
    url: https://www.pingcap.com/community/events/
    selectors:
      item: "a[href*='/community/'][href*='event']"
      title: "a"
      link_attr: href
      date: null

  # Databricks — Events (HTML)
  - name: Databricks Events
    kind: html
    category: event
    url: https://www.databricks.com/events
    selectors:
      item: "a[href^='/events/']"
      title: "a"
      link_attr: href
      date: null

  # MongoDB — Events (HTML)
  - name: MongoDB Events
    kind: html
    category: event
    url: https://www.mongodb.com/events
    selectors:
      item: "a[href^='/events/']"
      title: "a"
      link_attr: href
      date: null

  # Pinecone — Events/Webinars (HTML)
  - name: Pinecone Events
    kind: html
    category: webinar
    url: https://www.pinecone.io/events/
    selectors:
      item: "main a[href^='/events/'], main a[href^='/webinars/'], main a[href^='/learn/']"
      title: "a"
      link_attr: href
      date: null

  # Redis — Events (HTML)
  - name: Redis Events
    kind: html
    category: event
    url: https://redis.com/company/events/
    selectors:
      item: "a[href^='/company/events/'], a[href^='/company/webinars/'], a[href^='/blog/']"
      title: "a"
      link_attr: href
      date: null

  # CockroachDB — Events (HTML)
  - name: CockroachDB Events
    kind: html
    category: event
    url: https://www.cockroachlabs.com/events/
    selectors:
      item: "a[href^='/events/']"
      title: "a"
      link_attr: href
      date: null

  # DataStax — Events (HTML)
  - name: DataStax Events
    kind: html
    category: event
    url: https://www.datastax.com/events
    selectors:
      item: "a[href^='/events/'], a[href^='/webinars/']"
      title: "a"
      link_attr: href
      date: null

  # MariaDB — Events (WordPress; RSS)
  - name: MariaDB Events
    kind: rss
    category: event
    url: https://mariadb.com/events/feed/
