sources:
  - name: ClickHouse Blog
    kind: rss
    category: blog
    url: https://clickhouse.com/rss.xml

  - name: ScyllaDB Blog
    kind: rss
    category: blog
    url: https://www.scylladb.com/feed/

  - name: Yugabyte Blog
    kind: rss
    category: blog
    url: https://www.yugabyte.com/blog/feed/

  - name: PingCAP (TiDB) Blog
    kind: rss
    category: blog
    url: https://www.pingcap.com/blog/feed/

  - name: CockroachDB Blog
    kind: rss
    category: blog
    url: https://www.cockroachlabs.com/blog/index.xml

  - name: DataStax Blog
    kind: rss
    category: blog
    url: https://www.datastax.com/blog/rss.xml

  - name: MariaDB (Resources Blog)
    kind: rss
    category: blog
    url: https://mariadb.com/resources/blog/feed/

  - name: Redis Blog
    kind: rss
    category: blog
    url: https://redis.com/blog/feed/

  # Databricks: use official release notes feed
  - name: Databricks Release Notes
    kind: rss
    category: release
    url: https://docs.databricks.com/en/release-notes/index.xml

  # MongoDB official feeds (map to "news")
  - name: MongoDB Security Bulletins
    kind: rss
    category: news
    url: https://www.mongodb.com/alerts/rss

  - name: MongoDB Press Releases
    kind: rss
    category: news
    url: https://investors.mongodb.com/rss/press-releases.xml

  # Broad database news (map all to "news")
  - name: DB-Engines Ranking
    kind: rss
    category: news
    url: https://db-engines.com/en/rss/ranking.xml

  - name: InfoQ – Database
    kind: rss
    category: news
    url: https://feed.infoq.com/database

  - name: PostgreSQL News (official)
    kind: rss
    category: news
    url: https://www.postgresql.org/news.rss

  - name: Planet PostgreSQL
    kind: rss
    category: news
    url: https://planet.postgresql.org/rss20.xml

  - name: MySQL Official Blog
    kind: rss
    category: blog
    url: https://blogs.oracle.com/mysql/rss

  - name: BigQuery Release Notes
    kind: rss
    category: release
    url: https://cloud.google.com/feeds/bigquery-release-notes.xml

  - name: Cloud Spanner Release Notes
    kind: rss
    category: release
    url: https://cloud.google.com/feeds/cloud-spanner-release-notes.xml
