name: Weekly Competitor Watcher (Mon 9:00 IST)

on:
  schedule:
    # 09:00 IST = 03:30 UTC every Monday
    - cron: "30 3 * * 1"
  workflow_dispatch: {}  # lets you trigger it manually too

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run weekly digest
        env:
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DRY_RUN: "false"
          TZ: "Asia/Kolkata"
          SINCE_HOURS: "0"            # disable recency filter for this test
          SEED_LATEST_PER_SOURCE: "3" # include top 3 per source if DB is empty
          MAX_ITEMS_PER_SOURCE: "10"  # cap volume
        run: python run_daily.py
